services:
  torch-splatting:
    build: .
    working_dir: /opt/torch-splatting
    volumes:
      - ../:/opt/torch-splatting
      - ./result/test:/opt/torch-splatting/result/test
      - ./entrypoint.sh:/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
volumes:
  B075X65R3X:
